package com.fortytwoq.mvc.dao;

import com.fortytwoq.mvc.model.TestCase;
import com.fortytwoq.mvc.model.TestCaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int countByExample(TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int deleteByExample(TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int insert(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int insertSelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    List<TestCase> selectByExample(TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    TestCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestCase record, @Param("example") TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestCase record, @Param("example") TestCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestCase record);
}