package com.fortytwoq.mvc.dao;

import com.fortytwoq.mvc.model.TestCaseStep;
import com.fortytwoq.mvc.model.TestCaseStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestCaseStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int countByExample(TestCaseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int deleteByExample(TestCaseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int insert(TestCaseStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int insertSelective(TestCaseStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    List<TestCaseStep> selectByExample(TestCaseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    TestCaseStep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestCaseStep record, @Param("example") TestCaseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestCaseStep record, @Param("example") TestCaseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestCaseStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestCaseStep record);
}