package com.fortytwoq.mvc.dao;

import com.fortytwoq.mvc.model.TestModule;
import com.fortytwoq.mvc.model.TestModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int countByExample(TestModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int deleteByExample(TestModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int insert(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int insertSelective(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    List<TestModule> selectByExample(TestModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    TestModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestModule record, @Param("example") TestModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestModule record, @Param("example") TestModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestModule record);
}