package com.fortytwoq.mvc.model;

import java.util.Date;

public class TestCaseStep {
    private Integer id;

    private Integer testCaseId;

    private Integer subStep;

    private Integer stepType;

    private String stepId;

    private String seq;

    private String waitElementLocated;

    private String elementXpth;

    private String elementAction;

    private String clean;

    private String elementValue;

    private Date pauseSec;

    private Date createDate;

    private Date updateDate;
    
    

    @Override
	public String toString() {
		return "TestCaseStep [id=" + id + ", testCaseId=" + testCaseId + ", subStep=" + subStep + ", stepType="
				+ stepType + ", stepId=" + stepId + ", seq=" + seq + ", waitElementLocated=" + waitElementLocated
				+ ", elementXpth=" + elementXpth + ", elementAction=" + elementAction + ", clean=" + clean
				+ ", elementValue=" + elementValue + ", pauseSec=" + pauseSec + ", createDate=" + createDate
				+ ", updateDate=" + updateDate + "]";
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.id
     *
     * @param id the value for test_case_step.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.test_case_id
     *
     * @return the value of test_case_step.test_case_id
     *
     * @mbggenerated
     */
    public Integer getTestCaseId() {
        return testCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.test_case_id
     *
     * @param testCaseId the value for test_case_step.test_case_id
     *
     * @mbggenerated
     */
    public void setTestCaseId(Integer testCaseId) {
        this.testCaseId = testCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.sub_step
     *
     * @return the value of test_case_step.sub_step
     *
     * @mbggenerated
     */
    public Integer getSubStep() {
        return subStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.sub_step
     *
     * @param subStep the value for test_case_step.sub_step
     *
     * @mbggenerated
     */
    public void setSubStep(Integer subStep) {
        this.subStep = subStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.step_type
     *
     * @return the value of test_case_step.step_type
     *
     * @mbggenerated
     */
    public Integer getStepType() {
        return stepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.step_type
     *
     * @param stepType the value for test_case_step.step_type
     *
     * @mbggenerated
     */
    public void setStepType(Integer stepType) {
        this.stepType = stepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.step_id
     *
     * @return the value of test_case_step.step_id
     *
     * @mbggenerated
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.step_id
     *
     * @param stepId the value for test_case_step.step_id
     *
     * @mbggenerated
     */
    public void setStepId(String stepId) {
        this.stepId = stepId == null ? null : stepId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.seq
     *
     * @return the value of test_case_step.seq
     *
     * @mbggenerated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.seq
     *
     * @param seq the value for test_case_step.seq
     *
     * @mbggenerated
     */
    public void setSeq(String seq) {
        this.seq = seq == null ? null : seq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.wait_element_located
     *
     * @return the value of test_case_step.wait_element_located
     *
     * @mbggenerated
     */
    public String getWaitElementLocated() {
        return waitElementLocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.wait_element_located
     *
     * @param waitElementLocated the value for test_case_step.wait_element_located
     *
     * @mbggenerated
     */
    public void setWaitElementLocated(String waitElementLocated) {
        this.waitElementLocated = waitElementLocated == null ? null : waitElementLocated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.element_xpth
     *
     * @return the value of test_case_step.element_xpth
     *
     * @mbggenerated
     */
    public String getElementXpth() {
        return elementXpth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.element_xpth
     *
     * @param elementXpth the value for test_case_step.element_xpth
     *
     * @mbggenerated
     */
    public void setElementXpth(String elementXpth) {
        this.elementXpth = elementXpth == null ? null : elementXpth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.element_action
     *
     * @return the value of test_case_step.element_action
     *
     * @mbggenerated
     */
    public String getElementAction() {
        return elementAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.element_action
     *
     * @param elementAction the value for test_case_step.element_action
     *
     * @mbggenerated
     */
    public void setElementAction(String elementAction) {
        this.elementAction = elementAction == null ? null : elementAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.clean
     *
     * @return the value of test_case_step.clean
     *
     * @mbggenerated
     */
    public String getClean() {
        return clean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.clean
     *
     * @param clean the value for test_case_step.clean
     *
     * @mbggenerated
     */
    public void setClean(String clean) {
        this.clean = clean == null ? null : clean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.element_value
     *
     * @return the value of test_case_step.element_value
     *
     * @mbggenerated
     */
    public String getElementValue() {
        return elementValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.element_value
     *
     * @param elementValue the value for test_case_step.element_value
     *
     * @mbggenerated
     */
    public void setElementValue(String elementValue) {
        this.elementValue = elementValue == null ? null : elementValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.pause_sec
     *
     * @return the value of test_case_step.pause_sec
     *
     * @mbggenerated
     */
    public Date getPauseSec() {
        return pauseSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.pause_sec
     *
     * @param pauseSec the value for test_case_step.pause_sec
     *
     * @mbggenerated
     */
    public void setPauseSec(Date pauseSec) {
        this.pauseSec = pauseSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.create_date
     *
     * @return the value of test_case_step.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.create_date
     *
     * @param createDate the value for test_case_step.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case_step.update_date
     *
     * @return the value of test_case_step.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case_step.update_date
     *
     * @param updateDate the value for test_case_step.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TestCaseStep other = (TestCaseStep) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTestCaseId() == null ? other.getTestCaseId() == null : this.getTestCaseId().equals(other.getTestCaseId()))
            && (this.getSubStep() == null ? other.getSubStep() == null : this.getSubStep().equals(other.getSubStep()))
            && (this.getStepType() == null ? other.getStepType() == null : this.getStepType().equals(other.getStepType()))
            && (this.getStepId() == null ? other.getStepId() == null : this.getStepId().equals(other.getStepId()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getWaitElementLocated() == null ? other.getWaitElementLocated() == null : this.getWaitElementLocated().equals(other.getWaitElementLocated()))
            && (this.getElementXpth() == null ? other.getElementXpth() == null : this.getElementXpth().equals(other.getElementXpth()))
            && (this.getElementAction() == null ? other.getElementAction() == null : this.getElementAction().equals(other.getElementAction()))
            && (this.getClean() == null ? other.getClean() == null : this.getClean().equals(other.getClean()))
            && (this.getElementValue() == null ? other.getElementValue() == null : this.getElementValue().equals(other.getElementValue()))
            && (this.getPauseSec() == null ? other.getPauseSec() == null : this.getPauseSec().equals(other.getPauseSec()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTestCaseId() == null) ? 0 : getTestCaseId().hashCode());
        result = prime * result + ((getSubStep() == null) ? 0 : getSubStep().hashCode());
        result = prime * result + ((getStepType() == null) ? 0 : getStepType().hashCode());
        result = prime * result + ((getStepId() == null) ? 0 : getStepId().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getWaitElementLocated() == null) ? 0 : getWaitElementLocated().hashCode());
        result = prime * result + ((getElementXpth() == null) ? 0 : getElementXpth().hashCode());
        result = prime * result + ((getElementAction() == null) ? 0 : getElementAction().hashCode());
        result = prime * result + ((getClean() == null) ? 0 : getClean().hashCode());
        result = prime * result + ((getElementValue() == null) ? 0 : getElementValue().hashCode());
        result = prime * result + ((getPauseSec() == null) ? 0 : getPauseSec().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}