package com.fortytwoq.mvc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TestCaseStepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public TestCaseStepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdIsNull() {
            addCriterion("test_case_id is null");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdIsNotNull() {
            addCriterion("test_case_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdEqualTo(Integer value) {
            addCriterion("test_case_id =", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdNotEqualTo(Integer value) {
            addCriterion("test_case_id <>", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdGreaterThan(Integer value) {
            addCriterion("test_case_id >", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_case_id >=", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdLessThan(Integer value) {
            addCriterion("test_case_id <", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdLessThanOrEqualTo(Integer value) {
            addCriterion("test_case_id <=", value, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdIn(List<Integer> values) {
            addCriterion("test_case_id in", values, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdNotIn(List<Integer> values) {
            addCriterion("test_case_id not in", values, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdBetween(Integer value1, Integer value2) {
            addCriterion("test_case_id between", value1, value2, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andTestCaseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("test_case_id not between", value1, value2, "testCaseId");
            return (Criteria) this;
        }

        public Criteria andSubStepIsNull() {
            addCriterion("sub_step is null");
            return (Criteria) this;
        }

        public Criteria andSubStepIsNotNull() {
            addCriterion("sub_step is not null");
            return (Criteria) this;
        }

        public Criteria andSubStepEqualTo(Integer value) {
            addCriterion("sub_step =", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepNotEqualTo(Integer value) {
            addCriterion("sub_step <>", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepGreaterThan(Integer value) {
            addCriterion("sub_step >", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub_step >=", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepLessThan(Integer value) {
            addCriterion("sub_step <", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepLessThanOrEqualTo(Integer value) {
            addCriterion("sub_step <=", value, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepIn(List<Integer> values) {
            addCriterion("sub_step in", values, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepNotIn(List<Integer> values) {
            addCriterion("sub_step not in", values, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepBetween(Integer value1, Integer value2) {
            addCriterion("sub_step between", value1, value2, "subStep");
            return (Criteria) this;
        }

        public Criteria andSubStepNotBetween(Integer value1, Integer value2) {
            addCriterion("sub_step not between", value1, value2, "subStep");
            return (Criteria) this;
        }

        public Criteria andStepTypeIsNull() {
            addCriterion("step_type is null");
            return (Criteria) this;
        }

        public Criteria andStepTypeIsNotNull() {
            addCriterion("step_type is not null");
            return (Criteria) this;
        }

        public Criteria andStepTypeEqualTo(Integer value) {
            addCriterion("step_type =", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotEqualTo(Integer value) {
            addCriterion("step_type <>", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeGreaterThan(Integer value) {
            addCriterion("step_type >", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("step_type >=", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeLessThan(Integer value) {
            addCriterion("step_type <", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeLessThanOrEqualTo(Integer value) {
            addCriterion("step_type <=", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeIn(List<Integer> values) {
            addCriterion("step_type in", values, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotIn(List<Integer> values) {
            addCriterion("step_type not in", values, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeBetween(Integer value1, Integer value2) {
            addCriterion("step_type between", value1, value2, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("step_type not between", value1, value2, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepIdIsNull() {
            addCriterion("step_id is null");
            return (Criteria) this;
        }

        public Criteria andStepIdIsNotNull() {
            addCriterion("step_id is not null");
            return (Criteria) this;
        }

        public Criteria andStepIdEqualTo(String value) {
            addCriterion("step_id =", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdNotEqualTo(String value) {
            addCriterion("step_id <>", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdGreaterThan(String value) {
            addCriterion("step_id >", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdGreaterThanOrEqualTo(String value) {
            addCriterion("step_id >=", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdLessThan(String value) {
            addCriterion("step_id <", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdLessThanOrEqualTo(String value) {
            addCriterion("step_id <=", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdLike(String value) {
            addCriterion("step_id like", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdNotLike(String value) {
            addCriterion("step_id not like", value, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdIn(List<String> values) {
            addCriterion("step_id in", values, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdNotIn(List<String> values) {
            addCriterion("step_id not in", values, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdBetween(String value1, String value2) {
            addCriterion("step_id between", value1, value2, "stepId");
            return (Criteria) this;
        }

        public Criteria andStepIdNotBetween(String value1, String value2) {
            addCriterion("step_id not between", value1, value2, "stepId");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(String value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(String value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(String value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(String value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(String value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(String value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLike(String value) {
            addCriterion("seq like", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotLike(String value) {
            addCriterion("seq not like", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<String> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<String> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(String value1, String value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(String value1, String value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedIsNull() {
            addCriterion("wait_element_located is null");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedIsNotNull() {
            addCriterion("wait_element_located is not null");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedEqualTo(String value) {
            addCriterion("wait_element_located =", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedNotEqualTo(String value) {
            addCriterion("wait_element_located <>", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedGreaterThan(String value) {
            addCriterion("wait_element_located >", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedGreaterThanOrEqualTo(String value) {
            addCriterion("wait_element_located >=", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedLessThan(String value) {
            addCriterion("wait_element_located <", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedLessThanOrEqualTo(String value) {
            addCriterion("wait_element_located <=", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedLike(String value) {
            addCriterion("wait_element_located like", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedNotLike(String value) {
            addCriterion("wait_element_located not like", value, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedIn(List<String> values) {
            addCriterion("wait_element_located in", values, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedNotIn(List<String> values) {
            addCriterion("wait_element_located not in", values, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedBetween(String value1, String value2) {
            addCriterion("wait_element_located between", value1, value2, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andWaitElementLocatedNotBetween(String value1, String value2) {
            addCriterion("wait_element_located not between", value1, value2, "waitElementLocated");
            return (Criteria) this;
        }

        public Criteria andElementXpthIsNull() {
            addCriterion("element_xpth is null");
            return (Criteria) this;
        }

        public Criteria andElementXpthIsNotNull() {
            addCriterion("element_xpth is not null");
            return (Criteria) this;
        }

        public Criteria andElementXpthEqualTo(String value) {
            addCriterion("element_xpth =", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthNotEqualTo(String value) {
            addCriterion("element_xpth <>", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthGreaterThan(String value) {
            addCriterion("element_xpth >", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthGreaterThanOrEqualTo(String value) {
            addCriterion("element_xpth >=", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthLessThan(String value) {
            addCriterion("element_xpth <", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthLessThanOrEqualTo(String value) {
            addCriterion("element_xpth <=", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthLike(String value) {
            addCriterion("element_xpth like", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthNotLike(String value) {
            addCriterion("element_xpth not like", value, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthIn(List<String> values) {
            addCriterion("element_xpth in", values, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthNotIn(List<String> values) {
            addCriterion("element_xpth not in", values, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthBetween(String value1, String value2) {
            addCriterion("element_xpth between", value1, value2, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementXpthNotBetween(String value1, String value2) {
            addCriterion("element_xpth not between", value1, value2, "elementXpth");
            return (Criteria) this;
        }

        public Criteria andElementActionIsNull() {
            addCriterion("element_action is null");
            return (Criteria) this;
        }

        public Criteria andElementActionIsNotNull() {
            addCriterion("element_action is not null");
            return (Criteria) this;
        }

        public Criteria andElementActionEqualTo(String value) {
            addCriterion("element_action =", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionNotEqualTo(String value) {
            addCriterion("element_action <>", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionGreaterThan(String value) {
            addCriterion("element_action >", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionGreaterThanOrEqualTo(String value) {
            addCriterion("element_action >=", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionLessThan(String value) {
            addCriterion("element_action <", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionLessThanOrEqualTo(String value) {
            addCriterion("element_action <=", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionLike(String value) {
            addCriterion("element_action like", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionNotLike(String value) {
            addCriterion("element_action not like", value, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionIn(List<String> values) {
            addCriterion("element_action in", values, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionNotIn(List<String> values) {
            addCriterion("element_action not in", values, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionBetween(String value1, String value2) {
            addCriterion("element_action between", value1, value2, "elementAction");
            return (Criteria) this;
        }

        public Criteria andElementActionNotBetween(String value1, String value2) {
            addCriterion("element_action not between", value1, value2, "elementAction");
            return (Criteria) this;
        }

        public Criteria andCleanIsNull() {
            addCriterion("clean is null");
            return (Criteria) this;
        }

        public Criteria andCleanIsNotNull() {
            addCriterion("clean is not null");
            return (Criteria) this;
        }

        public Criteria andCleanEqualTo(String value) {
            addCriterion("clean =", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanNotEqualTo(String value) {
            addCriterion("clean <>", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanGreaterThan(String value) {
            addCriterion("clean >", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanGreaterThanOrEqualTo(String value) {
            addCriterion("clean >=", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanLessThan(String value) {
            addCriterion("clean <", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanLessThanOrEqualTo(String value) {
            addCriterion("clean <=", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanLike(String value) {
            addCriterion("clean like", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanNotLike(String value) {
            addCriterion("clean not like", value, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanIn(List<String> values) {
            addCriterion("clean in", values, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanNotIn(List<String> values) {
            addCriterion("clean not in", values, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanBetween(String value1, String value2) {
            addCriterion("clean between", value1, value2, "clean");
            return (Criteria) this;
        }

        public Criteria andCleanNotBetween(String value1, String value2) {
            addCriterion("clean not between", value1, value2, "clean");
            return (Criteria) this;
        }

        public Criteria andElementValueIsNull() {
            addCriterion("element_value is null");
            return (Criteria) this;
        }

        public Criteria andElementValueIsNotNull() {
            addCriterion("element_value is not null");
            return (Criteria) this;
        }

        public Criteria andElementValueEqualTo(String value) {
            addCriterion("element_value =", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueNotEqualTo(String value) {
            addCriterion("element_value <>", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueGreaterThan(String value) {
            addCriterion("element_value >", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueGreaterThanOrEqualTo(String value) {
            addCriterion("element_value >=", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueLessThan(String value) {
            addCriterion("element_value <", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueLessThanOrEqualTo(String value) {
            addCriterion("element_value <=", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueLike(String value) {
            addCriterion("element_value like", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueNotLike(String value) {
            addCriterion("element_value not like", value, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueIn(List<String> values) {
            addCriterion("element_value in", values, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueNotIn(List<String> values) {
            addCriterion("element_value not in", values, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueBetween(String value1, String value2) {
            addCriterion("element_value between", value1, value2, "elementValue");
            return (Criteria) this;
        }

        public Criteria andElementValueNotBetween(String value1, String value2) {
            addCriterion("element_value not between", value1, value2, "elementValue");
            return (Criteria) this;
        }

        public Criteria andPauseSecIsNull() {
            addCriterion("pause_sec is null");
            return (Criteria) this;
        }

        public Criteria andPauseSecIsNotNull() {
            addCriterion("pause_sec is not null");
            return (Criteria) this;
        }

        public Criteria andPauseSecEqualTo(Date value) {
            addCriterionForJDBCDate("pause_sec =", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecNotEqualTo(Date value) {
            addCriterionForJDBCDate("pause_sec <>", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecGreaterThan(Date value) {
            addCriterionForJDBCDate("pause_sec >", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pause_sec >=", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecLessThan(Date value) {
            addCriterionForJDBCDate("pause_sec <", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pause_sec <=", value, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecIn(List<Date> values) {
            addCriterionForJDBCDate("pause_sec in", values, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecNotIn(List<Date> values) {
            addCriterionForJDBCDate("pause_sec not in", values, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pause_sec between", value1, value2, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andPauseSecNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pause_sec not between", value1, value2, "pauseSec");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_case_step
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_case_step
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}