package com.fortytwoq.mvc.model;

import java.util.Date;

public class TestCase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.test_case_id
     *
     * @mbggenerated
     */
    private String testCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.test_module_id
     *
     * @mbggenerated
     */
    private Integer testModuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.case_name
     *
     * @mbggenerated
     */
    private String caseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.menu_module_value
     *
     * @mbggenerated
     */
    private String menuModuleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.menu_function_value
     *
     * @mbggenerated
     */
    private String menuFunctionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.class_module_name
     *
     * @mbggenerated
     */
    private String classModuleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.class_function_name
     *
     * @mbggenerated
     */
    private String classFunctionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_case.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.id
     *
     * @return the value of test_case.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.id
     *
     * @param id the value for test_case.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.test_case_id
     *
     * @return the value of test_case.test_case_id
     *
     * @mbggenerated
     */
    public String getTestCaseId() {
        return testCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.test_case_id
     *
     * @param testCaseId the value for test_case.test_case_id
     *
     * @mbggenerated
     */
    public void setTestCaseId(String testCaseId) {
        this.testCaseId = testCaseId == null ? null : testCaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.test_module_id
     *
     * @return the value of test_case.test_module_id
     *
     * @mbggenerated
     */
    public Integer getTestModuleId() {
        return testModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.test_module_id
     *
     * @param testModuleId the value for test_case.test_module_id
     *
     * @mbggenerated
     */
    public void setTestModuleId(Integer testModuleId) {
        this.testModuleId = testModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.case_name
     *
     * @return the value of test_case.case_name
     *
     * @mbggenerated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.case_name
     *
     * @param caseName the value for test_case.case_name
     *
     * @mbggenerated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.menu_module_value
     *
     * @return the value of test_case.menu_module_value
     *
     * @mbggenerated
     */
    public String getMenuModuleValue() {
        return menuModuleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.menu_module_value
     *
     * @param menuModuleValue the value for test_case.menu_module_value
     *
     * @mbggenerated
     */
    public void setMenuModuleValue(String menuModuleValue) {
        this.menuModuleValue = menuModuleValue == null ? null : menuModuleValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.menu_function_value
     *
     * @return the value of test_case.menu_function_value
     *
     * @mbggenerated
     */
    public String getMenuFunctionValue() {
        return menuFunctionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.menu_function_value
     *
     * @param menuFunctionValue the value for test_case.menu_function_value
     *
     * @mbggenerated
     */
    public void setMenuFunctionValue(String menuFunctionValue) {
        this.menuFunctionValue = menuFunctionValue == null ? null : menuFunctionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.class_module_name
     *
     * @return the value of test_case.class_module_name
     *
     * @mbggenerated
     */
    public String getClassModuleName() {
        return classModuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.class_module_name
     *
     * @param classModuleName the value for test_case.class_module_name
     *
     * @mbggenerated
     */
    public void setClassModuleName(String classModuleName) {
        this.classModuleName = classModuleName == null ? null : classModuleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.class_function_name
     *
     * @return the value of test_case.class_function_name
     *
     * @mbggenerated
     */
    public String getClassFunctionName() {
        return classFunctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.class_function_name
     *
     * @param classFunctionName the value for test_case.class_function_name
     *
     * @mbggenerated
     */
    public void setClassFunctionName(String classFunctionName) {
        this.classFunctionName = classFunctionName == null ? null : classFunctionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.enable
     *
     * @return the value of test_case.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.enable
     *
     * @param enable the value for test_case.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.create_date
     *
     * @return the value of test_case.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.create_date
     *
     * @param createDate the value for test_case.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_case.update_date
     *
     * @return the value of test_case.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_case.update_date
     *
     * @param updateDate the value for test_case.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TestCase other = (TestCase) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTestCaseId() == null ? other.getTestCaseId() == null : this.getTestCaseId().equals(other.getTestCaseId()))
            && (this.getTestModuleId() == null ? other.getTestModuleId() == null : this.getTestModuleId().equals(other.getTestModuleId()))
            && (this.getCaseName() == null ? other.getCaseName() == null : this.getCaseName().equals(other.getCaseName()))
            && (this.getMenuModuleValue() == null ? other.getMenuModuleValue() == null : this.getMenuModuleValue().equals(other.getMenuModuleValue()))
            && (this.getMenuFunctionValue() == null ? other.getMenuFunctionValue() == null : this.getMenuFunctionValue().equals(other.getMenuFunctionValue()))
            && (this.getClassModuleName() == null ? other.getClassModuleName() == null : this.getClassModuleName().equals(other.getClassModuleName()))
            && (this.getClassFunctionName() == null ? other.getClassFunctionName() == null : this.getClassFunctionName().equals(other.getClassFunctionName()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_case
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTestCaseId() == null) ? 0 : getTestCaseId().hashCode());
        result = prime * result + ((getTestModuleId() == null) ? 0 : getTestModuleId().hashCode());
        result = prime * result + ((getCaseName() == null) ? 0 : getCaseName().hashCode());
        result = prime * result + ((getMenuModuleValue() == null) ? 0 : getMenuModuleValue().hashCode());
        result = prime * result + ((getMenuFunctionValue() == null) ? 0 : getMenuFunctionValue().hashCode());
        result = prime * result + ((getClassModuleName() == null) ? 0 : getClassModuleName().hashCode());
        result = prime * result + ((getClassFunctionName() == null) ? 0 : getClassFunctionName().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}